name: Supabase External Heartbeat

on:
  schedule:
    - cron: '0 0 */5 * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Heartbeat Table
        env:
          SUPABASE_TOKEN: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          curl -f -i -X POST "https://dagodyvkqkdsknzuzbtj.supabase.co/rest/v1/heartbeat" \
          -H "apikey: $SUPABASE_TOKEN" \
          -H "Authorization: Bearer $SUPABASE_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{}'
