name: Supabase External Heartbeat

on:
  schedule:
    - cron: '0 0 */5 * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Heartbeat Table
        run: |
          curl -f -i -X POST "https://supabase.co" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}'
